// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czgugzmsdxtsjjsotdic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6Z3Vnem1zZHh0c2pqc290ZGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjE4NzIsImV4cCI6MjA3MjI5Nzg3Mn0.m95Il1oh0I-jMGbV1XA90JHhj_WBs-ZVA2HFMb6A35A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});